### ISSUE TITLE
Objective of RNX

### ISSUE THREAD

**Issue by sudhirvkumar** [atomicits/purescript-rnx#27]
1. Keep the library up to date with the releases of React Native within a few days of React Native Releases.
2. Use PureScript Type System to enable developers to build applications easily and using editor as a partner. More details in a different Issue / discussion
3. Documentation. Haskell libraries generally suffer from documentation I would like to avoid that and provide a clear documentation instead of digging into the source code to figure things out.
4. Follow Semver so its easy to understand breaking changes. Will keep publishing 0.x.x releases till React Native 1.0 is released. Also clear release notes so that people understand the changes easily.
5. RNX will be a repository of not just React Native components but also ports of other awesome react native libraries. Need to decide about the native modules. I would like to keep the libraries required to a minimum or just to purescript-react.

**Comment by sudhirvkumar** [comment]
@doolse @pkamenarsky

Your comments are appreciated

**Comment by doolse** [comment]
On 5, i'm not so sure that it's a good idea to have third party components in the same core "purescript-rnx" library because they may not keep pace with the actual react-native releases, probably better to release separate libraries for third party components e.g. "purescript-rnx-mapview" etc..

**Comment by sudhirvkumar** [comment]
@doolse What I meant was `ports` of the 3rd party components, with very little or no FFI and mostly written in PureScript. I don't want to have too many libraries and figuring out what is where.

I am thinking of implementation agnostic library `purescript-rnx` and `purescript-rnx-thermite` for the implementation.

I am still thinking about what the function Signature of the `onPress` and other events will be wont that be implementation specific. I would like to avoid have polymorphic types if they can (or should) be specific!

**Comment by doolse** [comment]
@sudhirvkumar Sure that sounds good, I see `purescript-rnx` as being the low level React Native library which matches the React Native docs with properties and elements as closely as possible. So essentially exactly what you have already in `RNX.Components, RNX.Props, RNX.Events`. This would allow greatest flexibility for people who want to build libraries on top of RNX. 

There certainly is a need for safer higher level which could also be part of `purescript-rnx` in another module, e.g. `RNX.Safer.Components`. So for example the sort of thing I would expect to see is:

```purescript
import RNX.Components as U

activityIndicator :: {animating::Boolean, color::Color, size :: IndicatorSize } 
    -> Array Props 
    -> ReactElement 
activityIndicator p props = U.activityIndicator $ [ 
      animating p.animating
    , pColor p.color
    , indicatorSize p.size ] <> props
```

So you don't want to use `EventHandlerContext eff props state result` for events? I agree that it's a pretty horrible type signature but it certainly doesn't tie to a specific implementation (besides react of course!)

**Comment by sudhirvkumar** [comment]
@doolse I was thinking in the similar lines... now the issue is platform specific components, props, styles and API I would like them to be type safe too... check this issue https://github.com/atomicits/purescript-rnx/issues/28

Why shouldn't RNX be high level enough at the component level?

would appreciate your inputs

**Comment by sudhirvkumar** [comment]
@doolse I believe a single safer one is better isn't it? if we can figure out implementation independent way of handling things and still type safe

What I mean is... activityIndicator is a component with specific properties, some required others optional so why don't we protect developers from making mistakes by using the Type System? There is nothing generic. `purescript-react` is generic. RNX can restrict the properties based on the component and platform right? activityIndicator is not generic component. It has a specific purpose.

**Comment by doolse** [comment]
@sudhirvkumar I agree. I can live without the low-level library if the high level library doesn't tie me to Thermite. 

I'm going to have a go at creating a type safe listView component as a test, with all the supported properties. My first thought is to separate mandatory and optional properties with records for both, but the only nice way to specify the optional properties would be using the record update syntax:

```purescript
_ { renderSectionHeader = .. } 
```

I will keep you posted with how I go.

**Comment by doolse** [comment]
I think until Row constraints are added to purescript ( https://github.com/purescript/purescript/issues/469 )
we are limited with what we can do safely but also with a decent syntax, as you can't easily subset of a row apart from row update syntax, so this is what I had for a test of what it might look like:

```purescript
foreign import data ListViewDataSource :: * -> *
foreign import data Undefineable :: * -> *
foreign import mapUndefined :: forall a b. (a -> b) -> Undefineable a -> Undefineable b

type ListViewProps sid rid = {initialListSize::Int, renderSeparator:: sid -> rid -> Boolean -> ReactElement}

listView :: forall a sid rid. ListViewDataSource a -> (a -> ReactElement) -> (ListViewProps sid rid -> ListViewProps sid rid) -> ReactElement
listView dataSource renderRow p = createElement U.listViewClass (fixProps $ unsafeCoerce $ p $ unsafeCoerce {dataSource, renderRow}) []
  where
  fixProps props = props { renderSeparator = mapUndefined mkFn3 props.renderSeparator }
```

Which could be used like:

```purescript
listView dataSource renderRow _ { initialListSize = 20 }
```

But this relies on the fact that you don't actually use the passed in `ListViewProps` to update anything, as they will all be undefined. E.g. this would break:

```purescript
listView dataSource renderRow \p -> p { initialListSize = p.initialListSize + 12 }
```

 Not exactly typesafe :(
